M48
; DRILL file {KiCad 8.0.1} date 2024-04-22T08:31:39-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-22T08:31:39-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0500
%
G90
G05
T1
X4.3581Y-2.6
X4.3581Y-2.8677
T2
X4.6597Y-2.7408
M30
